# Generated by Django 4.0.5 on 2022-08-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_rename_firstname_form_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='dob',
            field=models.DateField(),
        ),
    ]
